// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful to verify connectivity.",
  inputSchema: { text: z.string().min(1).describe("Text to echo back.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ text }) => ({ content: [{ type: "text", text }] })
});

// src/lib/mcp/tools/list-shop-products.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";

// src/data/shopProducts.ts
var CATEGORY_LABEL = {
  poster: "Affiche",
  collector: "Collector",
  apparel: "V\xEAtement",
  sneakers: "Chaussure",
  music: "Musique",
  manga: "Manga & BD",
  daily: "Quotidien",
  lovacoins: "LovaCoins Exclusif"
};
var SEEDS = [
  // ===== AFFICHES / POSTERS (12) =====
  { name: "Affiche N\xE9on Ruri no Houseki", category: "poster", tag: "\xC9dition limit\xE9e", price: 24, description: "Tirage gicl\xE9e 50\xD770 cm sur papier mat 250g, finition n\xE9on magenta. Num\xE9rot\xE9e et sign\xE9e AnimemomentsAnimeofficiel.", source: "youtube" },
  { name: "Poster Holographique Anime Moments", category: "poster", tag: "Holo", price: 29, description: "Poster A2 imprim\xE9 sur film holographique, reflets arc-en-ciel selon l'angle. Tube cartonn\xE9 inclus.", source: "both" },
  { name: "Affiche Glow-in-Dark TikTok Drop", category: "poster", tag: "Phosphorescent", price: 32, description: "Encre phosphorescente activ\xE9e \xE0 la lumi\xE8re, brille pendant 6h dans le noir. Format 60\xD790 cm.", source: "tiktok" },
  { name: "Triptyque Moments Forts S1", category: "poster", tag: "Set de 3", price: 49, description: "Trois posters 30\xD740 cm formant une sc\xE8ne panoramique. Best-of saison 1 de la cha\xEEne YouTube.", source: "youtube" },
  { name: "Affiche Minimaliste Madoka", category: "poster", tag: "Art print", price: 19, description: "Style art d\xE9co minimaliste, papier coton 300g. \xC9dition open de 500 exemplaires.", source: "youtube" },
  { name: "Poster Vintage Manga Anim\xE9", category: "poster", tag: "R\xE9tro", price: 22, description: "Inspiration affiche cin\xE9ma japonaise des ann\xE9es 80, papier vieilli kraft. 50\xD770 cm.", source: "both" },
  { name: "Affiche XXL Mur Lovanet", category: "poster", tag: "Mural", price: 59, description: "Format mural 100\xD7140 cm, id\xE9al pour chambre gamer. Impression haute r\xE9solution.", source: "tiktok" },
  { name: "Poster Lenticulaire 3D Anime", category: "poster", tag: "3D lenticulaire", price: 39, description: "Effet 3D et changement d'image selon l'angle. Encadr\xE9 bois noir 30\xD740 cm.", source: "both" },
  { name: "Affiche Calligraphie Kanji Lovanet", category: "poster", tag: "Signature", price: 25, description: "Calligraphie kanji \xE0 l'encre de Chine, hommage \xE0 la cha\xEEne Lovanet. Papier washi 40\xD760 cm.", source: "youtube" },
  { name: "Set Mini-Posters Episodes Cultes", category: "poster", tag: "Pack x6", price: 34, description: "Six mini-posters A4 des \xE9pisodes les plus vus de la cha\xEEne. Tube collector inclus.", source: "youtube" },
  { name: "Poster Cyberpunk TikTok Edit", category: "poster", tag: "N\xE9o-Tokyo", price: 27, description: "Composition cyberpunk inspir\xE9e des edits TikTok viraux. Finition mate 50\xD770 cm.", source: "tiktok" },
  { name: "Affiche Premium Encadr\xE9e Alu", category: "poster", tag: "Encadr\xE9", price: 79, description: "Tirage Hahnem\xFChle 70\xD7100 cm encadr\xE9 aluminium bross\xE9. Pr\xEAt \xE0 accrocher.", source: "both" },
  // ===== OBJETS DE COLLECTION / COLLECTOR (13) =====
  { name: "Figurine LED Anime Glow 24cm", category: "collector", tag: "Collector", price: 89, description: "Figurine PVC 24 cm, socle LED RGB pilotable. \xC9dition limit\xE9e \xE0 500 exemplaires num\xE9rot\xE9s.", source: "youtube" },
  { name: "Statue Premium \xD1LL\xD1 Resin", category: "collector", tag: "\xC9dition 100", price: 249, description: "Statue r\xE9sine peinte main, hauteur 32 cm, socle marbre. Certificat d'authenticit\xE9.", source: "both" },
  { name: "Nendoroid Anime Moments", category: "collector", tag: "Chibi", price: 59, description: "Figurine chibi 10 cm articul\xE9e avec 3 visages interchangeables et accessoires.", source: "youtube" },
  { name: "Bust Half-Scale Madoka", category: "collector", tag: "Demi-buste", price: 179, description: "Buste demi-\xE9chelle, 20 cm de haut, finition mate premium. Bo\xEEte collector incluse.", source: "youtube" },
  { name: "Set Pin's \xC9mail Officiels", category: "collector", tag: "Pack x10", price: 39, description: "10 pin's \xE9mail dur, design exclusif AnimemomentsAnimeofficiel. Carte support cartonn\xE9e.", source: "tiktok" },
  { name: "Vinyle Picture Disc Lovanet", category: "collector", tag: 'Vinyle 12"', price: 34, description: "Vinyle picture disc 33 tours avec artwork anime, bande-son officielle Lovanet.", source: "both" },
  { name: "Carte Holo Tirage Limit\xE9", category: "collector", tag: "Trading card", price: 14, description: "Carte holographique format trading, scell\xE9e. Tirage 1000 exemplaires num\xE9rot\xE9s.", source: "tiktok" },
  { name: "Funko Style Anime Officiel", category: "collector", tag: "Vinyl figure", price: 29, description: "Figurine vinyle stylis\xE9e 10 cm, bo\xEEte fen\xEAtre. Premi\xE8re \xE9dition sign\xE9e.", source: "youtube" },
  { name: "Diorama LED Sc\xE8ne Culte", category: "collector", tag: "Diorama", price: 199, description: "Diorama 25\xD725 cm avec \xE9clairage LED int\xE9gr\xE9, t\xE9l\xE9commande RGB. Pi\xE8ce unique.", source: "youtube" },
  { name: "M\xE9daille M\xE9tal Anniversaire", category: "collector", tag: "M\xE9tal", price: 24, description: "M\xE9daille zamak finition or bross\xE9, coffret velours. \xC9dition anniversaire cha\xEEne.", source: "both" },
  { name: "Manga Artbook Officiel", category: "collector", tag: "Artbook", price: 49, description: "200 pages d'illustrations, storyboards et croquis exclusifs. Couverture rigide.", source: "youtube" },
  { name: "Boule de Cristal Hologramme", category: "collector", tag: "Cristal 3D", price: 44, description: "Boule cristal grav\xE9e laser avec personnage en 3D et socle LED. Diam\xE8tre 8 cm.", source: "tiktok" },
  { name: "Coffret Collector Saison 1", category: "collector", tag: "Box set", price: 129, description: "Coffret rigide contenant artbook, pin's, poster, m\xE9daille et carte. \xC9dition fans.", source: "youtube" },
  // ===== VÊTEMENTS / APPAREL (15) =====
  { name: "Hoodie Oversize N\xE9on Lovanet", category: "apparel", tag: "Streetwear", price: 79, description: "Sweat capuche oversize 320g, broderie n\xE9on dos. Coton bio certifi\xE9. Tailles XS \xE0 XXL.", source: "both" },
  { name: "T-shirt Heavyweight \xD1LL\xD1", category: "apparel", tag: "Heavyweight", price: 35, description: "T-shirt \xE9pais 240g coupe boxy, s\xE9rigraphie poitrine + dos. 100% coton peign\xE9.", source: "tiktok" },
  { name: "Crewneck Anime Moments Vintage", category: "apparel", tag: "Vintage wash", price: 65, description: "Sweat ras-du-cou d\xE9lavage stone wash. Patch brod\xE9 manche gauche.", source: "youtube" },
  { name: "Veste Bomber Reversible Manga", category: "apparel", tag: "Bomber", price: 119, description: "Bomber r\xE9versible noir/magenta, doublure satin imprim\xE9e. Manches \xE9lastiqu\xE9es.", source: "both" },
  { name: "Tee Long Sleeve Glitch Edit", category: "apparel", tag: "Long sleeve", price: 42, description: "Manches longues coupe oversize, print glitch sur manche. S\xE9rigraphie haute densit\xE9.", source: "tiktok" },
  { name: "Hoodie Zip-Up Cyberpunk", category: "apparel", tag: "Full zip", price: 89, description: "Sweat zipp\xE9 technique avec poches lat\xE9rales, capuche doubl\xE9e. Print dos all-over.", source: "youtube" },
  { name: "Shorts Cargo Streetwear", category: "apparel", tag: "Cargo", price: 55, description: "Short cargo ample avec poches lat\xE9rales zipp\xE9es. Imprim\xE9 katakana cuisse.", source: "tiktok" },
  { name: "Casquette Brod\xE9e Lovanet", category: "apparel", tag: "Cap", price: 29, description: "Casquette 6 panneaux structur\xE9e, broderie 3D logo Lovanet. Snapback ajustable.", source: "both" },
  { name: "Bonnet Beanie Magenta Glow", category: "apparel", tag: "Beanie", price: 22, description: "Bonnet maille c\xF4tel\xE9e, patch tiss\xE9 Anime Moments. Acrylique doux.", source: "youtube" },
  { name: "Tee Tie-Dye Magenta Cyan", category: "apparel", tag: "Tie-dye", price: 39, description: "T-shirt tie-dye r\xE9alis\xE9 \xE0 la main, chaque pi\xE8ce est unique. Coton lourd 220g.", source: "tiktok" },
  { name: "Veste Coach Anime Officiel", category: "apparel", tag: "Coach jacket", price: 95, description: "Veste coach nylon l\xE9ger, pressions devant, broderie dos AnimemomentsAnimeofficiel.", source: "both" },
  { name: "Pantalon Jogger Tech N\xE9on", category: "apparel", tag: "Jogger", price: 69, description: "Pantalon tech-fleece coupe slim, bandes r\xE9fl\xE9chissantes lat\xE9rales. Cheville zipp\xE9e.", source: "youtube" },
  { name: "Chaussettes Pack x3 Logo", category: "apparel", tag: "Pack x3", price: 19, description: "Trois paires de chaussettes hautes coton, broderie logo cheville. Taille unique 39-45.", source: "tiktok" },
  { name: "Polo R\xE9tro Anime Club", category: "apparel", tag: "Polo", price: 49, description: "Polo piqu\xE9 coton, broderie poitrine style college japonais. Coupe ajust\xE9e.", source: "youtube" },
  { name: "Robe T-Shirt Oversize Tokyo", category: "apparel", tag: "Tee-dress", price: 45, description: "Robe t-shirt longue oversize, print Tokyo nuit dos. Coton bio fluide.", source: "both" },
  // ===== CHAUSSURES / SNEAKERS (10) =====
  { name: "Sneakers High-Top LED Glow", category: "sneakers", tag: "Hype", price: 159, description: "Baskets montantes avec semelle LED rechargeable USB, 7 modes lumineux. Tailles 36-46.", source: "tiktok" },
  { name: "Runners Tech Neon Mesh", category: "sneakers", tag: "Runner", price: 129, description: "Runner technique mesh respirant, semelle EVA l\xE9g\xE8re, accents n\xE9on magenta.", source: "youtube" },
  { name: "Skate Shoes Anime Print", category: "sneakers", tag: "Skate", price: 89, description: "Toile vulcanis\xE9e style skate, print int\xE9gral anime sur la tige. Renforts orteils.", source: "tiktok" },
  { name: "Boots Cyberpunk Platform", category: "sneakers", tag: "Plateforme", price: 179, description: "Bottes plateforme 5 cm, finition vinyle noir, lacets rouges. \xC9dition capsule.", source: "youtube" },
  { name: "Mules Slides Logo Emboss\xE9", category: "sneakers", tag: "Slides", price: 49, description: "Claquettes EVA inject\xE9, logo emboss\xE9 sur la bride. Confort absolu \xE9t\xE9.", source: "tiktok" },
  { name: "Sneakers Low Magenta Suede", category: "sneakers", tag: "Suede", price: 119, description: "Baskets basses daim magenta, semelle gomme blanche. Bo\xEEte collector.", source: "both" },
  { name: "Trainers Bicolore Cyan/Noir", category: "sneakers", tag: "Trainer", price: 99, description: "Trainer vintage bicolore, languette \xE9paisse, semelle gum. Coupe r\xE9tro 90s.", source: "youtube" },
  { name: "Chunky Sneakers Anime Beast", category: "sneakers", tag: "Chunky", price: 149, description: "Chunky sole 6 cm, multi-couches mesh et cuir, broderie cr\xE9ature anime talon.", source: "tiktok" },
  { name: "Sneakers Co-Lab Lovanet", category: "sneakers", tag: "Co-lab", price: 199, description: "Collaboration exclusive Lovanet. Num\xE9rot\xE9es sur la semelle.", source: "both" },
  { name: "Chaussons Maison Anime Plush", category: "sneakers", tag: "Cozy", price: 35, description: "Chaussons peluche imprim\xE9s personnages anime, semelle antid\xE9rapante.", source: "youtube" },
  // ===== MUSIQUE / MUSIC (8) =====
  { name: "Vinyle OST Ruri no Houseki", category: "music", tag: 'Vinyle 12"', price: 32, description: "Bande originale officielle press\xE9e sur vinyle 180g color\xE9 magenta translucide.", source: "youtube" },
  { name: "Cassette Mixtape TikTok Edits", category: "music", tag: "Cassette", price: 14, description: "Mixtape K7 audio limit\xE9e \xE0 300 ex, compilation des edits TikTok viraux.", source: "tiktok" },
  { name: "EP Digital Lovanet Lo-Fi", category: "music", tag: "Digital", price: 9, description: "EP 6 titres lo-fi anime t\xE9l\xE9chargeable en FLAC et MP3 320kbps. Artwork HD inclus.", source: "both" },
  { name: "CD Collector Box Anime Beats", category: "music", tag: "CD digipack", price: 19, description: "Double CD digipack, 24 titres remasteris\xE9s, livret 24 pages.", source: "youtube" },
  { name: "Casque Audio N\xE9on NLNQ", category: "music", tag: "Audio gear", price: 119, description: "Casque circum-aural sans-fil 40h d'autonomie, anneaux LED r\xE9actifs au son.", source: "both" },
  { name: "Platine Vinyle Compact Magenta", category: "music", tag: "Hardware", price: 189, description: "Platine vinyle Bluetooth coloris magenta, capot transparent, pr\xE9-ampli int\xE9gr\xE9.", source: "youtube" },
  { name: 'Single 7" Opening Cyber', category: "music", tag: "Single", price: 12, description: "Single 7 pouces avec opening + ending, jaquette holographique.", source: "tiktok" },
  { name: "Synthwave Pack Sample NLNQ", category: "music", tag: "Sample pack", price: 24, description: "150 samples synthwave royalty-free, kicks, snares, leads, presets Serum.", source: "both" },
  // ===== MANGA & BD / COMICS (8) =====
  { name: "Manga Tome 1 Anime Moments", category: "manga", tag: "Tome 01", price: 11, description: "Premier tome 192 pages, format poche, jaquette r\xE9versible et marque-page collector.", source: "youtube" },
  { name: "BD Hardcover Lovanet Saga", category: "manga", tag: "Hardcover", price: 29, description: "Roman graphique cartonn\xE9 120 pages couleur, papier mat 150g.", source: "both" },
  { name: "Light Novel Lovanet Chronicles", category: "manga", tag: "Light novel", price: 16, description: "Light novel illustr\xE9 320 pages, 12 illustrations couleur pleine page.", source: "youtube" },
  { name: "Doujinshi \xC9dition Fan-Club", category: "manga", tag: "Doujin", price: 18, description: "Doujinshi A5 64 pages, tirage limit\xE9 500 ex num\xE9rot\xE9s \xE0 la main.", source: "tiktok" },
  { name: "Manga Box Set Saison 1", category: "manga", tag: "Coffret 6 tomes", price: 79, description: "Coffret carton rigide 6 premiers tomes + poster exclusif double face.", source: "youtube" },
  { name: "Webtoon Print Anniversaire", category: "manga", tag: "Webtoon", price: 22, description: "Premi\xE8re impression papier d'un webtoon viral, format vertical 21\xD740 cm.", source: "tiktok" },
  { name: "Artbook Storyboard Edition", category: "manga", tag: "Storyboard", price: 39, description: "Artbook 180 pages de storyboards bruts, croquis et planches d'animation.", source: "youtube" },
  { name: "Comics One-Shot \xD1LL\xD1 Origin", category: "manga", tag: "One-shot", price: 14, description: "Comics one-shot format US 32 pages couleur, couverture variante exclusive.", source: "both" },
  // ===== OBJETS DU QUOTIDIEN / DAILY (10) =====
  { name: "Mug Thermor\xE9actif Anime", category: "daily", tag: "Thermo", price: 18, description: "Mug c\xE9ramique 350ml qui r\xE9v\xE8le son artwork avec une boisson chaude.", source: "youtube" },
  { name: "Gourde Inox N\xE9on 750ml", category: "daily", tag: "Inox", price: 26, description: "Gourde double paroi inox, garde froid 24h / chaud 12h. Bouchon sport.", source: "tiktok" },
  { name: "Tote Bag Canvas Manga", category: "daily", tag: "Tote", price: 19, description: "Sac tote 320g coton recycl\xE9, s\xE9rigraphie deux couleurs grand format.", source: "both" },
  { name: "Tapis de Souris XXL RGB", category: "daily", tag: "Gaming", price: 35, description: "Tapis 90\xD740 cm, contour LED RGB USB, surface micro-tiss\xE9e pour souris gaming.", source: "youtube" },
  { name: "Bougie Parfum\xE9e Tokyo Rain", category: "daily", tag: "Bougie", price: 24, description: "Bougie cire de soja 200g, senteurs pluie, c\xE8dre et yuzu. M\xE8che en bois.", source: "tiktok" },
  { name: "Plaid Sherpa Anime Moments", category: "daily", tag: "Plaid", price: 49, description: "Plaid sherpa 150\xD7200 cm ultra doux, imprim\xE9 all-over, doublure peluche.", source: "both" },
  { name: "Stickers Pack Holographiques", category: "daily", tag: "Stickers x20", price: 12, description: "20 stickers holographiques d\xE9coup\xE9s, vinyle waterproof r\xE9sistant UV.", source: "tiktok" },
  { name: "Carnet A5 Pages Pointill\xE9es", category: "daily", tag: "Stationery", price: 16, description: "Carnet bullet journal 192 pages, papier 100g, \xE9lastique et marque-page.", source: "youtube" },
  { name: "Lampe LED Akari Cube Anime", category: "daily", tag: "D\xE9co", price: 39, description: "Cube lumineux 15 cm, 16 millions de couleurs, t\xE9l\xE9commande et appli mobile.", source: "both" },
  { name: "Coque Smartphone Holo Magenta", category: "daily", tag: "Accessoire", price: 22, description: "Coque silicone renforc\xE9e effet holographique, compatible MagSafe.", source: "tiktok" },
  // ===== LOVACOINS EXCLUSIF (4) =====
  { name: "Titre Holographique: Otaku Supr\xEAme", category: "lovacoins", tag: "Digital", price: 1500, currency: "LC", description: "D\xE9bloque un titre holographique unique pour ton profil. Effet visuel incroyable.", source: "both" },
  { name: "Cadre Avatar N\xE9on Flamme", category: "lovacoins", tag: "Digital", price: 800, currency: "LC", description: "Un cadre de profil anim\xE9 avec des flammes n\xE9on magenta. Rends ton avatar \xE9pique.", source: "youtube" },
  { name: "Ticket Watch Party Priv\xE9e", category: "lovacoins", tag: "Digital", price: 2500, currency: "LC", description: "Rejoins l'\xE9quipe Lovanet pour une s\xE9ance de visionnage en direct exclusive.", source: "tiktok" },
  { name: "Banni\xE8re Profil Cyber-City", category: "lovacoins", tag: "Digital", price: 1200, currency: "LC", description: "Banni\xE8re de profil anim\xE9e repr\xE9sentant une ville cyberpunk sous la pluie.", source: "both" }
];
var SHOP_CATEGORIES = Object.keys(CATEGORY_LABEL).map((id) => ({
  id,
  label: CATEGORY_LABEL[id]
}));
var SHOP_PRODUCTS = [
  ...SEEDS.filter((s) => s.category === "lovacoins").map((s, i) => ({
    id: `am-lc-${String(i + 1).padStart(3, "0")}`,
    name: s.name,
    category: s.category,
    tag: s.tag,
    price: s.price,
    currency: s.currency || "EUR",
    description: s.description,
    source: s.source
  })),
  ...SEEDS.filter((s) => s.category !== "lovacoins").map((s, i) => ({
    id: `am-${String(i + 1).padStart(3, "0")}`,
    name: s.name,
    category: s.category,
    tag: s.tag,
    price: s.price,
    currency: s.currency || "EUR",
    description: s.description,
    source: s.source
  }))
];

// src/lib/mcp/tools/list-shop-products.ts
var list_shop_products_default = defineTool2({
  name: "list_shop_products",
  title: "List shop products",
  description: "Return the public Lovanet shop catalog (posters, apparel, sneakers, manga, music, daily). Supports optional category filter and result limit.",
  inputSchema: {
    category: z2.enum(["poster", "collector", "apparel", "sneakers", "music", "manga", "daily"]).optional().describe("Restrict the results to a single category."),
    limit: z2.number().int().min(1).max(200).optional().describe("Maximum number of products to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ category, limit }) => {
    const max = limit ?? 50;
    const filtered = category ? SHOP_PRODUCTS.filter((p) => p.category === category) : SHOP_PRODUCTS;
    const items = filtered.slice(0, max);
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { count: items.length, total: filtered.length, items }
    };
  }
});

// src/lib/mcp/tools/list-shop-categories.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_shop_categories_default = defineTool3({
  name: "list_shop_categories",
  title: "List shop categories",
  description: "Return the list of product categories available in the Lovanet shop.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(SHOP_CATEGORIES, null, 2) }],
    structuredContent: { categories: SHOP_CATEGORIES }
  })
});

// src/lib/mcp/tools/search-shop-products.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";

// src/data/videos.ts
var videos = [
  { id: "bGFUthZjGd4", title: "So It's Something Else \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 09", date: "2026-05-26", recent: true },
  { id: "5Fr9M1GBDBo", title: "You Did A Good Job \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 08", date: "2026-05-22", recent: true },
  { id: "i0Pz8tmOy8o", title: "I Was Working So Much Harder! \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 07", date: "2026-05-18", recent: true },
  { id: "E6X7VsKuMsM", title: "I'm Just So Impressed With Your Determination \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 06", date: "2026-05-14", recent: true },
  { id: "DtEDLCrliHs", title: "You Haven't Forgotten About The Task At Hand \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 05", date: "2026-05-10", recent: true },
  { id: "S0BmS2xG8tg", title: "What Do You Want The Most ? GOLD \u{1F602}", series: "Ruri no Houseki", channel: "AnimeOfficial", episode: "Ep. 04", date: "2026-05-06", recent: true }
];

// src/data/generatedProducts.ts
var THEMES = [
  "Sakura",
  "Kitsune",
  "Ronin",
  "Shinobi",
  "Kaiju",
  "Neko",
  "Onmyoji",
  "Yokai",
  "Samurai",
  "Miko",
  "Oni",
  "Tengu",
  "Kirin",
  "Ryu",
  "Hoshi",
  "Tsuki",
  "Hikari",
  "Kaze",
  "Mizu",
  "Hana",
  "Yuki",
  "Kumo",
  "Tori",
  "Ame",
  "Neo Tokyo",
  "Akihabara",
  "Shibuya",
  "Harajuku",
  "Kyoto",
  "Osaka",
  "Mecha",
  "Gundam Style",
  "Cyber Katana",
  "Neon City",
  "Chibi Squad",
  "Magical Girl",
  "Idol Live",
  "Shonen Hero",
  "Shojo Dream",
  "Isekai Quest",
  "Battle Arena",
  "Dojo Legend",
  "Onsen",
  "Matsuri",
  "Sakura Festival",
  "Moonlight",
  "Sunset Bay",
  "Starlight",
  "Rainbow Wave",
  "Prism"
];
var STYLES = [
  "Neon",
  "Chibi",
  "Retro",
  "Hologramme",
  "Cyberpunk",
  "Kawaii",
  "Vintage",
  "Glitch",
  "Pastel",
  "Fluo",
  "Dark",
  "Sunset",
  "Aqua",
  "Rose Gold",
  "Chrome",
  "Vaporwave",
  "Line Art",
  "Watercolor",
  "Ink Wash",
  "Sketch"
];
var LINES = [
  {
    category: "poster",
    types: ["Affiche", "Poster", "Tirage art", "Triptyque", "Mural XXL", "Poster lenticulaire"],
    tags: ["A2", "A1", "50x70", "Holo", "Mat premium", "Edition limitee"],
    base: 18,
    range: 42,
    desc: (n, t, s) => `${n} \u2014 impression giclee HD, papier 250g mat, finition ${s.toLowerCase()}. Univers ${t}, signe AnimemomentsAnimeofficiel. Tube renforce, expedition suivie 3-7j.`
  },
  {
    category: "collector",
    types: ["Figurine", "Statue", "Nendoroid", "Buste", "Diorama", "Boule cristal", "Vinyle picture disc", "Artbook"],
    tags: ["Edition 500", "Numerote", "Resine", "PVC premium", "Coffret", "Rare"],
    base: 34,
    range: 220,
    desc: (n, t, s) => `${n} \u2014 piece collection ${s.toLowerCase()} inspiree de ${t}. Peinture main, socle premium, boite fenetre, certificat d'authenticite AnimemomentsAnimeofficiel.`
  },
  {
    category: "apparel",
    types: ["Hoodie", "T-shirt", "Crewneck", "Bomber", "Coach jacket", "Long sleeve", "Kimono street", "Varsity"],
    tags: ["Oversize", "Heavyweight 320g", "Coton bio", "Broderie", "All-over", "Streetwear"],
    base: 32,
    range: 95,
    desc: (n, t, s) => `${n} \u2014 piece streetwear ${s.toLowerCase()} oversize, coton 240-320g, serigraphie haute densite, broderie ${t}. XS-XXL. Livraison suivie.`
  },
  {
    category: "sneakers",
    types: ["Sneakers basses", "Sneakers hautes", "Runners", "Slip-on", "Chunky", "Skate"],
    tags: ["Edition capsule", "Numerote", "Cuir vegan", "Mesh", "Semelle epaisse", "Reflective"],
    base: 79,
    range: 140,
    desc: (n, t, s) => `${n} \u2014 silhouette ${s.toLowerCase()} univers ${t}. Tige mesh + cuir vegan, semelle EVA amortie, oeillets metal. Boite collector incluse.`
  },
  {
    category: "music",
    types: ['Vinyle 12"', "Vinyle picture", "OST double CD", "Cassette collector", "EP digital deluxe"],
    tags: ["OST", "Vinyle 180g", "Edition limitee", "Signe", "Bonus"],
    base: 19,
    range: 45,
    desc: (n, t, s) => `${n} \u2014 bande-son originale ${s.toLowerCase()} pour la serie ${t}. Pressage 180g, pochette holo, livret 12 pages avec artworks exclusifs.`
  },
  {
    category: "manga",
    types: ["Manga tome", "Coffret 3 tomes", "Coffret integrale", "Artbook", "Roman visuel", "BD"],
    tags: ["VF", "Collector", "Jaquette alt.", "Souple", "Rigide"],
    base: 9,
    range: 89,
    desc: (n, t, s) => `${n} \u2014 edition ${s.toLowerCase()} AnimemomentsAnimeofficiel. Papier bouffant, jaquette alternative, pages couleur bonus autour de l'univers ${t}.`
  },
  {
    category: "daily",
    types: ["Mug thermo", "Gourde inox", "Tote bag", "Tapis souris XXL", "Bougie parfumee", "Plaid sherpa", "Sticker pack", "Carnet A5", "Lampe LED", "Coque smartphone", "Porte-cles", "Casquette 3D", "Beanie", "Chaussettes", "Eventail sensu"],
    tags: ["Quotidien", "Cadeau", "Gaming", "Deco", "Accessoire"],
    base: 8,
    range: 42,
    desc: (n, t, s) => `${n} \u2014 objet quotidien ${s.toLowerCase()} finition premium. Materiau durable, impression resistante, packaging responsable. Design exclusif autour de ${t}.`
  }
];
function seededPrice(base, range, seed) {
  const v = seed * 2654435761 >>> 0;
  const n = base + v % range;
  return Math.max(base, Math.round(n));
}
var SOURCES = ["youtube", "tiktok", "both"];
function slugify(s) {
  return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "").slice(0, 80);
}
function generateProducts(count = 1500) {
  const out = [];
  const seen = /* @__PURE__ */ new Set();
  let i = 0;
  let attempts = 0;
  while (out.length < count && attempts < count * 6) {
    attempts++;
    const line = LINES[i % LINES.length];
    const type = line.types[Math.floor(i / LINES.length) % line.types.length];
    const theme = THEMES[(i * 3 + attempts) % THEMES.length];
    const style = STYLES[(i * 7 + attempts) % STYLES.length];
    const tag = line.tags[i % line.tags.length];
    const serie = String(1 + (i + attempts) % 240).padStart(3, "0");
    const name = `${type} ${style} ${theme} \xB7 \xC9dition ${serie}`;
    const sig = name;
    if (seen.has(sig)) {
      i++;
      continue;
    }
    seen.add(sig);
    const idNum = out.length + 1;
    const id = `gm-${String(idNum).padStart(5, "0")}`;
    const seed = idNum + 17;
    const price = seededPrice(line.base, line.range, seed);
    const compareAt = Math.round(price * (1.15 + seed % 40 / 100));
    const rating = 4 + seed % 10 / 10;
    const reviews = 12 + seed * 7 % 980;
    const sold = 40 + seed * 13 % 4800;
    const stock = 5 + seed % 200;
    const isDigital = line.category === "music" && seed % 3 === 0;
    const hasVideo = seed % 3 === 0;
    const vid = videos[seed % videos.length];
    out.push({
      id,
      slug: slugify(name) + "-" + id,
      name,
      category: line.category,
      tag,
      price,
      compareAt,
      rating: Number(rating.toFixed(1)),
      reviews,
      sold,
      stock,
      type: isDigital ? "digital" : "physical",
      brand: "AnimemomentsAnimeofficiel",
      description: line.desc(name, theme, style),
      bullets: [
        `Univers ${theme} \xB7 style ${style}`,
        `Finition premium, contr\xF4le qualit\xE9 en atelier`,
        `Emballage protecteur & suivi de colis`,
        `Retour offert sous 14 jours`
      ],
      specs: {
        R\u00E9f\u00E9rence: id.toUpperCase(),
        Marque: "AnimemomentsAnimeofficiel",
        Cat\u00E9gorie: line.category,
        \u00C9dition: serie,
        Th\u00E8me: theme,
        Style: style
      },
      shippingDays: isDigital ? "Instantan\xE9" : "3\u20137j",
      video: hasVideo ? vid.id : void 0,
      source: SOURCES[seed % SOURCES.length]
    });
    i++;
  }
  return out;
}
var ALL_PRODUCTS = [...SHOP_PRODUCTS, ...generateProducts(1500)];

// src/lib/mcp/tools/search-shop-products.ts
var CATEGORY_VALUES = ["poster", "collector", "apparel", "sneakers", "music", "manga", "daily"];
var SOURCE_VALUES = ["youtube", "tiktok", "both"];
var normalize = (value) => value.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").trim();
var searchableText = (product) => normalize(
  [
    product.name,
    product.description,
    product.tag,
    product.category,
    product.brand,
    product.type,
    product.source,
    ...product.bullets ?? [],
    ...Object.values(product.specs ?? {})
  ].filter(Boolean).join(" ")
);
var search_shop_products_default = defineTool4({
  name: "search_shop_products",
  title: "Search shop products",
  description: "Search the Lovanet shop catalog by keyword and filters such as category, product type, source, price range, stock, and sort order.",
  inputSchema: {
    query: z3.string().optional().describe("Keyword to search in product names, tags, descriptions, bullets, and specs."),
    category: z3.enum(CATEGORY_VALUES).optional().describe("Restrict results to one product category."),
    type: z3.enum(["physical", "digital"]).optional().describe("Restrict results to physical or digital products."),
    source: z3.enum(SOURCE_VALUES).optional().describe("Restrict results to YouTube, TikTok, or products connected to both."),
    minPrice: z3.number().optional().describe("Minimum product price in euros."),
    maxPrice: z3.number().optional().describe("Maximum product price in euros."),
    inStockOnly: z3.boolean().optional().describe("When true, only return products with stock above zero."),
    sort: z3.enum(["relevance", "price_asc", "price_desc", "rating", "sold"]).optional().describe("Result sort order. Default is relevance."),
    limit: z3.number().int().min(1).max(100).optional().describe("Maximum number of results to return. Default is 25.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ query, category, type, source, minPrice, maxPrice, inStockOnly, sort, limit }) => {
    const terms = normalize(query ?? "").split(/\s+/).filter(Boolean);
    const max = limit ?? 25;
    const scored = ALL_PRODUCTS.map((product, index) => {
      const haystack = searchableText(product);
      const name = normalize(product.name);
      const tag = normalize(product.tag);
      const score = terms.length ? terms.reduce((total, term) => {
        if (name.includes(term)) return total + 8;
        if (tag.includes(term)) return total + 5;
        if (haystack.includes(term)) return total + 2;
        return total;
      }, 0) : 1;
      return { product, score, index };
    }).filter(({ product, score }) => {
      if (terms.length && score <= 0) return false;
      if (category && product.category !== category) return false;
      if (type && product.type !== type) return false;
      if (source && product.source !== source) return false;
      if (typeof minPrice === "number" && product.price < minPrice) return false;
      if (typeof maxPrice === "number" && product.price > maxPrice) return false;
      if (inStockOnly && (product.stock ?? 1) <= 0) return false;
      return true;
    });
    const sorted = scored.sort((a, b) => {
      if (sort === "price_asc") return a.product.price - b.product.price;
      if (sort === "price_desc") return b.product.price - a.product.price;
      if (sort === "rating") return (b.product.rating ?? 0) - (a.product.rating ?? 0);
      if (sort === "sold") return (b.product.sold ?? 0) - (a.product.sold ?? 0);
      return b.score - a.score || a.index - b.index;
    });
    const items = sorted.slice(0, max).map(({ product, score }) => ({ ...product, searchScore: score }));
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: {
        count: items.length,
        total: sorted.length,
        query: query ?? "",
        filters: { category, type, source, minPrice, maxPrice, inStockOnly, sort: sort ?? "relevance" },
        items
      }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "pvgfxzzwuhjhfqsiylpr";
var mcp_default = defineMcp({
  name: "lovanet-mcp",
  title: "Lovanet MCP",
  version: "0.1.0",
  instructions: "Tools exposing the public Lovanet catalog. Use `echo` to test connectivity, `list_shop_categories` to discover categories, `list_shop_products` to browse products, and `search_shop_products` to search by keyword, price, source, type, stock, and category.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [echo_default, list_shop_categories_default, list_shop_products_default, search_shop_products_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
